//
//  Stub.swift
//  SwiftUISample
//
//  Created by Elon on 09/06/2019.
//  Copyright © 2019 Elon. All rights reserved.
//

import Foundation

struct Stub {
    let searchResult: String = """
    {
        "resultCount": 10,
        "results": [{
                "artistViewUrl": "https://itunes.apple.com/kr/developer/kakao-corp/id362057950?mt=8&uo=4",
                "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/bc/d7/83/bcd7830b-cf0e-6399-0048-0a6000f3f3b6/source/60x60bb.jpg",
                "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/bc/d7/83/bcd7830b-cf0e-6399-0048-0a6000f3f3b6/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/46/d3/49/46d34937-efda-8550-4e71-be34b1721d35/mzl.qeduvgms.png/552x414bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/dd/59/79/dd597935-6983-b4aa-67c3-c9c574132b8f/mzl.ikawfrlt.png/1024x768bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/9f/4f/d3/9f4fd323-034f-3614-fd69-a057ef7d7ef9/mzl.cllyeyjl.png/1024x768bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/3f/3a/86/3f3a8618-a645-3576-2f47-f8cb656b8461/mzl.dhxnwndp.png/1024x768bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/20/a7/0e/20a70ecd-f2c8-ccc1-7e3e-f703bf33313b/mzl.cunidotz.png/1024x768bb.png"
                ],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/bc/d7/83/bcd7830b-cf0e-6399-0048-0a6000f3f3b6/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/3d/88/97/3d88971c-cae6-fa6d-8e8b-22392309af26/pr_source.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/9b/71/be/9b71be28-4763-8fc4-0d80-eee68d7329b5/pr_source.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/8e/44/8e/8e448eba-b06a-7e90-7d0c-ab504fe17369/pr_source.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/6c/fb/d0/6cfbd032-e980-f45f-db62-70962e6c04b6/pr_source.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "Watch4-Watch4",
                    "iPhone5-iPhone5",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [
                    "iosUniversal"
                ],
                "trackCensoredName": "카카오톡 KakaoTalk",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4%ED%86%A1-kakaotalk/id362057947?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 2.5,
                "languageCodesISO2A": [
                    "EN",
                    "FR",
                    "DE",
                    "ID",
                    "IT",
                    "JA",
                    "KO",
                    "PT",
                    "RU",
                    "ZH",
                    "ES",
                    "TH",
                    "ZH",
                    "TR",
                    "VI"
                ],
                "fileSizeBytes": "445965312",
                "sellerUrl": "https://www.kakaocorp.com/service/KakaoTalk",
                "userRatingCountForCurrentVersion": 964,
                "trackContentRating": "4+",
                "trackId": 362057947,
                "trackName": "카카오톡 KakaoTalk",
                "currentVersionReleaseDate": "2019-05-31T02:18:29Z",
                "minimumOsVersion": "10.0",
                "releaseNotes": "[v8.4.1]\n• 버그 수정 및 안정성 개선\n\n[v8.4.0]\n• 말풍선 디자인 개편\n: 채팅방에서 사진과 동영상을 더 시원하게 볼 수 있어요.\n: 채팅방 배경화면색에 연한 하늘색이 추가되었어요.\n• 멀티 동영상 전송 시 안정성 개선\n• 친구 목록에 생일인 친구 표시\n: 다가오는 친구의 생일도 확인할 수 있어요. \n• 오픈채팅 선물하기 지원 \n: 이제 오픈채팅방에서도 선물할 수 있어요.\n• 알림음 6종 추가 (삼중톤 포함)",
                "sellerName": "Kakao Corp.",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "8.4.1",
                "genreIds": [
                    "6005",
                    "6007"
                ],
                "formattedPrice": "무료",
                "artistId": 362057950,
                "artistName": "Kakao Corp.",
                "genres": [
                    "소셜 네트워킹",
                    "생산성"
                ],
                "price": 0.00,
                "description": "* 업데이트를 하기 전에 항상 폰 백업 혹은 '이메일 계정 연결', '친구목록 내보내기' 등으로 중요한 데이터를 보관하시기를 권장합니다.\n\n** 카카오톡은 무료 앱입니다. 업데이트 또는 앱 설치 과정에서 일부 사용자에게 보여지는 앱스토어 $1결제 관련 메시지는 실제로 비용이 청구되지 않습니다. 자세한 내용은 애플에 문의해주시기 바랍니다.\n================================\n카카오톡을 이용하면  푸쉬 기능을 통해  즉각적으로 메시지를 받을 수 있고  사진, 동영상, 연락처 등의 멀티미디어도 간편하게 주고 받을 수 있습니다. 이제 SMS에서 벗어나 카카오톡으로 친구, 동료, 가족들과 보다 편리하고 다양한 멀티미디어 채팅을 시작해 보세요.\n\n- 카카오톡의 주요 기능 -\n\n* 전세계 어디서나 무료로 즐기는 그룹채팅 및 1:1 채팅\n카카오톡을 설치한 친구들간에는 국내뿐 아니라 해외에 있는 친구들과도 무료로 채팅을 즐길 수 있습니다.  기본적인 1:1 채팅뿐 아니라,  그룹 채팅을 통해 여러 친구들과 동시에  메시지, 사진, 동영상, 음악, 연락처 등을 간편하게 주고 받을 수 있습니다. (카카오톡은 WIFI 또는 3G를 이용합니다) \n\n*모임이 편리해지는 톡게시판\n모임 안내를 공지로 올리고, 일정과 투표로 더 쉽게 모여보세요. 게시판에 사진과 동영상, 파일을 올려두면 언제든지 찾아 볼 수 있습니다. \n\n*카톡하다 궁금할 때 #검색 \n카톡하다 궁금한게 생기면 따로 찾지말고 #검색으로 원하던 답을 한 눈에 찾아 보세요. \n\n*링크로 연결되는 오픈채팅\n친구 추가 없이 채팅하고 싶을 때 링크를 만들어서 대화할 수 있어요. 좋아하는 관심사나 스터디/모임으로 활용해 보세요. \n\n*전세계 어디서나 보이스톡, 뽀샤시한 얼굴로 페이스톡\n무제한 무료통화가 가능한 보이스톡으로 친구들과 이야기를 나누어 보세요. 페이스톡 영상통화는 감각적인 필터로 여러분의 얼굴을 더 아름답게 보여줄 수 있습니다. \n\n*카톡만 있다면 송금할 준비 끝\n계좌번호, 공인인증서, OTP 없이 카톡 친구에게 메시지 보내 듯 쉽게 송금할 수 있습니다.\n\n*카카오톡에서 콘텐츠를 즐긴다 \n카카오톡 채널에는 요즘 가장 핫한 소식과 TV영상, 웃긴 이야기, 뉴스, 웹툰 등 다양한 콘텐츠가 다 모여 있습니다. 최신 뉴스부터 재미있는 동영상까지 다양한 핫 콘텐츠를 카카오톡 내에서 바로 즐겨보세요.\n\n*유용하고 안전한 주문, 배송, 결제 등의 정보성 메시지, 알림톡\n스팸 문자에 불편하고 스미싱 문자에 불안하셨나요? 대표전화에는 문자 회신 못해 답답하셨나요?\n주문/결제/예약 내역이나 배송현황과 같이 여러분에게 꼭 필요한 정보들은 플러스친구가 알림톡으로 보내 드립니다.\n\n[서비스 접근 권한 안내]\n* 선택 접근 권한\n- 위치정보 : 지도 기능 사용시 위치 정보 검색 및 위치 공유\n- 연락처 : 친구 추가 및 연락처, 프로필 전송\n- 사진 : 프로필, 채팅방에 사진 및 멀티미디어 파일 제공\n- 마이크 : 보이스톡,페이스톡 통화 및 음성메시지 녹음\n- 카메라 : 친구추가를 위한 QR코드 촬영, 페이스톡 통화, 채팅방 멀티미디어 파일 제공\n- 캘린더 : 게시판 일정 정보를 캘린더에 저장\n\n* 선택 접근 권한은 동의하지 않아도 서비스 이용이 가능합니다.\n* 선택 접근 권한 미동의시 서비스 일부 기능의 정상적인 이용이 어려울 수 있습니다.",
                "bundleId": "com.iwilab.KakaoTalk",
                "releaseDate": "2010-03-18T07:00:00Z",
                "primaryGenreName": "Social Networking",
                "primaryGenreId": 6005,
                "averageUserRating": 3.0,
                "userRatingCount": 132185
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/kakao-corp/id362057950?mt=8&uo=4",
                "artworkUrl60": "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/50/25/b1/5025b12f-f5c5-8945-7ebd-495cae6a165b/source/60x60bb.jpg",
                "artworkUrl100": "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/50/25/b1/5025b12f-f5c5-8945-7ebd-495cae6a165b/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/50/25/b1/5025b12f-f5c5-8945-7ebd-495cae6a165b/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/43/d3/7f/43d37fd1-38bd-e952-cce7-8c2e498a38a4/mzl.fozqiuoh.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/a6/d9/43/a6d943d6-a4bf-ff4d-8eaa-fe3de4a83d01/mzl.jwdgwazy.png/696x696bb.png",
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/f2/01/5d/f2015d9d-14f8-dd83-cb8e-7d56e27b1c1d/pr_source.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/0c/a6/e4/0ca6e411-fee9-fc15-1a06-c3c277c6d61d/mzl.ifgqcitr.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/3f/c3/08/3fc30878-e66d-72d6-68f8-60f33093cab5/mzl.kxduqpuc.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/74/e7/6a/74e76a0e-2038-cd85-560f-0b0fed7d474d/mzl.iprzzajx.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/ab/e1/a4/abe1a4ac-635d-5667-d4a0-0a434ed344c2/mzl.msczermb.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "iPad2Wifi-iPad2Wifi",
                    "iPad23G-iPad23G",
                    "iPhone4S-iPhone4S",
                    "iPadThirdGen-iPadThirdGen",
                    "iPadThirdGen4G-iPadThirdGen4G",
                    "iPhone5-iPhone5",
                    "iPodTouchFifthGen-iPodTouchFifthGen",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPadMini-iPadMini",
                    "iPadMini4G-iPadMini4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [],
                "trackCensoredName": "카카오톡 치즈",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4%ED%86%A1-%EC%B9%98%EC%A6%88/id1132015103?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 4.0,
                "languageCodesISO2A": [
                    "EN",
                    "JA",
                    "KO",
                    "ZH"
                ],
                "fileSizeBytes": "134319104",
                "sellerUrl": "https://cheez.kakao.com",
                "userRatingCountForCurrentVersion": 44,
                "trackContentRating": "4+",
                "trackId": 1132015103,
                "trackName": "카카오톡 치즈",
                "currentVersionReleaseDate": "2019-06-05T01:35:38Z",
                "minimumOsVersion": "9.0",
                "releaseNotes": "치즈 필터 개편\n- 치즈 필터가 다양해졌어요! 마음에 쏙 드는 필터로 인생샷 남기세요.",
                "sellerName": "Kakao Corp.",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "4.3.1",
                "genreIds": [
                    "6008",
                    "6016"
                ],
                "formattedPrice": "무료",
                "artistId": 362057950,
                "artistName": "Kakao Corp.",
                "genres": [
                    "사진 및 비디오",
                    "엔터테인먼트"
                ],
                "price": 0.00,
                "description": "쫀득쫀득 치즈에서 프렌즈와 같이 놀아요!\n\n프렌즈와 함께 쫀득 스티커를 찍고 새로운 프사 놀이를 시작하세요.\n프로필콘으로 톡 프로필을 특별하게 바꿀 수 있어요.\n지금 치즈에서 카카오 프렌즈랑 같이 노는 새로운 방법을 만나세요!\n\n+ 비디오 촬영\n여러 번 끊어 찍기는 물론 음악과 함께 즐거운 순간을 생생하게 담을 수 있어요.\n\n+ 치즈톡 \n찍고! 입력하고! 보내고! 24시간 후엔 사라지는 움짤 채팅, 치즈톡을 만나보세요.\n\n+ 라이브 스티커\n쫀쫀하게 따라 다니는 라이브 스티커로 다양한 프사 놀이를 즐기세요. 프렌즈 친구들과 함께 놀 수 있어요.\n\n+ 뷰티필터\n자연스런 뷰티 필터로 티내지 말고 예뻐지세요. 대 반전 특수 필터로 깜짝 놀랄 모습을 담을 수도 있어요.\n\n+ 프로필콘\n프로필콘으로 톡 프로필을 특별하게 바꿔보세요. 매일의 내 기분을 표현하고 친구들과 공유하세요.\n\n치즈 소식 더보기\n홈페이지: https://cheez.kakao.com\n페이스북: https://facebook.com/KakaoTalkCheez\n인스타그램 ID: @kakaotalkcheez\n플러스친구 ID: @카카오톡치즈\n\n\n※ 서비스 접근 권한 안내\n\n* 선택적 접근 권한\n- 마이크 : 동영상 촬영시 사운드가 함께 녹음되는 기능을 제공하기 위해 사용\n- 앨범 : 사진 및 동영상을 저장하고 불러오기 위해 사용\n\n* 선택 접근 권한은 동의하지 않아도 서비스 이용이 가능합니다.\n* 선택 접근 권한 미동의시 서비스 일부 기능의 정상적인 이용이 어려울 수 있습니다.",
                "bundleId": "com.kakao.cheez",
                "releaseDate": "2016-09-07T07:04:17Z",
                "primaryGenreName": "Photo & Video",
                "primaryGenreId": 6008,
                "averageUserRating": 4.5,
                "userRatingCount": 20223
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/kakao-corp/id362057950?mt=8&uo=4",
                "artworkUrl60": "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/00/ce/a4/00cea44d-5f59-12c1-4ed5-9a6cf4408518/source/60x60bb.jpg",
                "artworkUrl100": "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/00/ce/a4/00cea44d-5f59-12c1-4ed5-9a6cf4408518/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/00/ce/a4/00cea44d-5f59-12c1-4ed5-9a6cf4408518/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/f8/61/cb/f861cb4c-fb72-e8c2-c5a0-2d8327eee3ae/mzl.uvgdjovc.png/696x696bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/31/6d/53/316d5361-c104-3fe6-da15-f822f7e6e4f6/mzl.obsrpzqj.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/ed/7b/d5/ed7bd5b0-ad9e-5f08-796f-56e04f993adf/mzl.survxtyl.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/b3/7f/fc/b37ffca7-08e3-9003-e64b-a64b6a69a8e3/mzl.onnwntoo.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/fc/4f/86/fc4f86fd-93b5-5671-552e-27437b60a5b4/mzl.ruejalzk.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "Watch4-Watch4",
                    "iPad2Wifi-iPad2Wifi",
                    "iPad23G-iPad23G",
                    "iPhone4S-iPhone4S",
                    "iPadThirdGen-iPadThirdGen",
                    "iPadThirdGen4G-iPadThirdGen4G",
                    "iPhone5-iPhone5",
                    "iPodTouchFifthGen-iPodTouchFifthGen",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPadMini-iPadMini",
                    "iPadMini4G-iPadMini4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [],
                "trackCensoredName": "카카오뮤직 KakaoMusic",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4%EB%AE%A4%EC%A7%81-kakaomusic/id696690152?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 2.0,
                "languageCodesISO2A": [
                    "KO"
                ],
                "fileSizeBytes": "116904960",
                "userRatingCountForCurrentVersion": 8,
                "trackContentRating": "4+",
                "trackId": 696690152,
                "trackName": "카카오뮤직 KakaoMusic",
                "currentVersionReleaseDate": "2019-05-14T23:59:58Z",
                "minimumOsVersion": "9.0",
                "releaseNotes": "- 일부 오류를 수정했습니다",
                "sellerName": "Kakao Corp.",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "4.50.5",
                "genreIds": [
                    "6011",
                    "6016"
                ],
                "formattedPrice": "무료",
                "artistId": 362057950,
                "artistName": "Kakao Corp.",
                "genres": [
                    "음악",
                    "엔터테인먼트"
                ],
                "price": 0.00,
                "description": "카카오뮤직에서 음악으로 일상을 공유하고 친구들과 소통해보세요~\n- 음악에 얽힌 이야기를 내 뮤직룸에 글과 이미지로 표현할 수 있어요\n- 친구 뮤직룸에서 친구가 직접 선곡한 음악을 전곡 감상할 수 있습니다.\n- 취향에 맞는 뮤직룸을 발견하고, 새로운 친구를 만들어보세요.\n\n► 주요 메뉴 소개\n1) PICK : 스타/브랜드, 다양한 이용자 뮤직룸을 발견하고 음악을 감상할 수 있어요.\n2) 피드 : 취향에 맞는 뮤직룸을 발견했다면, 친구로 추가하고 소식을 받아보세요. \n3) 내 뮤직룸 : 친구들과 함께 듣고 싶은 노래를 구매하고 글과 사진으로 나만의 사연을 꾸밀 수 있어요. \n4) 스토어 : 실시간 차트와 최신 음악, 1boon 뮤직, 테마 음악을 통해 다양한 음악을 발견해보세요.\n\n► 음악 상품 정보\n1) 매월 정기결제 (무제한 듣기) \n- 상품 설명: 카카오뮤직에 서비스되는 모든 곡을 매월 제한없이 감상 가능한 상품으로, 매번 결제하지않아도 결제일로부터 1개월마다 자동결제가 진행됨\n- 가격 : 매월 8,500원\n\n2) 30일권 (무제한 듣기)\n- 상품 설명: 카카오뮤직에 서비스되는 곡을 30일간 제한없이 감상 가능\n- 가격 : 9,900원\n\n3) 뮤직룸 곡 추가 (곡 구매)\n- 상품 설명: 곡을 내 뮤직룸에 추가할 수 있는 이용권 \n- 가격 : 1곡 1,200원, 5곡 4,900원, 10곡 8,900원, 25곡 22,000원, 50곡 43,000원\n\n► 정기결제 이용권 안내 및 해지\n- 정기결제 기간 만료 24시간 전에 구독을 취소하면 갱신되지 않습니다.\n- 정기결제 갱신시 기간 만료 24시간 이내에 금액 확인과 함께 결제됩니다.\n- 서비스 이용 시작 후 구매취소는 허용되지 않습니다.\n- 이용권 관리 및 해지는 iOS 장비의 [설정 > iTunes 및 App Store(혹은 Store) > Apple ID 보기 > 구독 관리]에서 설정할 수 있습니다.\n\n\n► 카카오뮤직 사용을 위한 접근 권한 안내\n1. 필수 권한 없음\n2. 선택 권한 (선택 권한을 허용하지 않아도 서비스 이용이 가능합니다)\n- 사진 앨범, 기본 카메라 : 프로필 및  뮤직룸 배경 이미지 설정, 뮤직룸 사연 이미지 업로드를 위해 필요합니다.\n\n► 궁금하신 점은 카카오 고객센터 또는 앱 내 [고객센터 > 1:1 문의하기]를 이용해주세요.\n- 문의 전화 : 1544-4058 (평일 10~19시)\n- 이메일 : music@kakaocorp.com\n\n\n► 이용약관은 아래 페이지에서 확인해주세요.\n - 카카오 서비스 약관 : http://www.kakao.com/ko/terms\n - 카카오 서비스 유료이용 약관 : https://billing-web.kakao.com/payment/service_terms_agreement\n - 카카오 서비스 개인정보처리방침 : https://www.kakao.com/ko/privacy\n - 카카오 운영정책 : https://www.kakao.com/policy/oppolicy\n - 카카오 청소년 보호정책 : https://www.kakao.com/policy/safeguard\n - 카카오 권리침해신고안내 : https://www.kakao.com/policy/right",
                "bundleId": "com.kakao.Music",
                "releaseDate": "2013-09-24T16:26:33Z",
                "primaryGenreName": "Music",
                "primaryGenreId": 6011,
                "averageUserRating": 2.5,
                "userRatingCount": 2162
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/kakaopay-corp/id1435127192?mt=8&uo=4",
                "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/17/50/1c/17501ca6-9eee-7f48-2c11-b9323b070a32/source/60x60bb.jpg",
                "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/17/50/1c/17501ca6-9eee-7f48-2c11-b9323b070a32/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/17/50/1c/17501ca6-9eee-7f48-2c11-b9323b070a32/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/6b/98/35/6b98350a-88f3-79c6-eb4d-c98c73f1f02b/pr_source.png/696x696bb.png",
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/4b/f0/b5/4bf0b5d2-d064-2a32-60d9-3f8d639e7c0e/pr_source.png/696x696bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/a1/b0/2d/a1b02d54-51b5-b7f3-57cc-e493b3b0166e/pr_source.png/696x696bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/41/d9/17/41d91745-56c0-200a-2ef5-8d6d48112c03/pr_source.png/696x696bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/5f/98/6b/5f986bd6-6fca-26d8-b978-bd8ce225720d/pr_source.png/696x696bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/e7/43/e1/e743e1ae-24ae-d3c7-9678-73ecd21beb6d/pr_source.png/696x696bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/9a/b0/b3/9ab0b3ac-09e4-f646-42d7-c2a3900d6967/pr_source.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [],
                "trackCensoredName": "카카오페이",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4%ED%8E%98%EC%9D%B4/id1464496236?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 4.0,
                "languageCodesISO2A": [
                    "EN",
                    "KO"
                ],
                "fileSizeBytes": "38597632",
                "userRatingCountForCurrentVersion": 157,
                "trackContentRating": "4+",
                "trackId": 1464496236,
                "trackName": "카카오페이",
                "currentVersionReleaseDate": "2019-05-28T11:05:50Z",
                "minimumOsVersion": "11.0",
                "sellerName": "Kakao Pay Co., Ltd.",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "1.0.0",
                "genreIds": [
                    "6015",
                    "6012"
                ],
                "formattedPrice": "무료",
                "artistId": 1435127192,
                "artistName": "kakaopay corp.",
                "genres": [
                    "금융",
                    "라이프 스타일"
                ],
                "price": 0.00,
                "description": "마음 놓고 금융하다, 카카오페이\n카카오페이가 만든 믿을 수 있는, 누구에게나 가까운, 덜 수고로운 금융 서비스를 사용해보세요.\n\n● 필요할 때 언제든 마음 놓고 결제\n- 앱 키고 첫 화면에서 바로\n- 지갑 없이도 자주 가는 편의점, 카페, 쇼핑몰 등 어디서나\n- 추가로 다양한 할인 혜택까지\n\n● 편하고 빠르게 마음 놓고 송금\n- 카톡 친구에게 쉽게\n- 계좌번호로 안전하게\n- 자주, 최근 보낸 친구 찾지 않고 바로\n\n● 돈이 보이니 마음 놓고 투자\n- 누구나 1만원부터 간편하게\n- 매일 오전 11시에 오픈되는 상품에 다양하게\n- 카카오페이에서 더욱 가볍게\n\n● 내돈 한눈에 확인\n- 카카오페이로 쓰고 받은 돈을 시간순으로\n- 앞으로 추가될 카드, 계좌 등도 한눈에\n\n● 금융이 일상이 되는 다양한 서비스\n- 멤버십, 청구서, 예약송금 등 다양한 서비스를 한 곳에서\n\n카카오페이로 간편하게, 쉽게, 자유롭게, 안전하게, 마음 놓고 금융하세요.\n금융이 일상이 됩니다.\n\n정보통신망법 제22조의2(접근권한에 대한 동의)에 따라 아래와 같이 카카오페이 앱 이용 시 필요한 접근권한을 안내해 드립니다.\n\n※ 선택 권한\n- 카메라: 송금 및 결제 시 코드 스캔 또는 촬영\n- 위치정보: 송금 및 결제 시 위치 확인\n- 저장공간: QR 이미지 저장\n* 선택 권한은 허용하지 않아도 해당 기능 외 서비스 사용이 가능합니다.\n\n※ 고객센터: 1644-7405 (평일 9시~18시)\n\n※ 분실 및 도용신고: 1833-7483 (24시간)",
                "bundleId": "com.kakaopay.payapp.store",
                "releaseDate": "2019-05-28T11:05:50Z",
                "primaryGenreName": "Finance",
                "primaryGenreId": 6015,
                "averageUserRating": 4.0,
                "userRatingCount": 157
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/iconnect/id435666963?mt=8&uo=4",
                "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/1e/0a/e7/1e0ae709-9a4a-0cae-7d08-7365a7dc3767/source/60x60bb.jpg",
                "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/1e/0a/e7/1e0ae709-9a4a-0cae-7d08-7365a7dc3767/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/1e/0a/e7/1e0ae709-9a4a-0cae-7d08-7365a7dc3767/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/5b/9b/a0/5b9ba090-8b44-177c-d797-6935009e8e10/mzl.mpdrwrfp.jpg/696x696bb.jpg",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/75/4d/87/754d875a-811e-9dfe-f343-7525c0493d64/mzl.adchugnu.jpg/696x696bb.jpg",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/66/68/8a/66688a82-26ee-4934-a3ec-de9368a13f62/mzl.nmkyiyxm.jpg/696x696bb.jpg",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/06/1b/ee/061beea0-7523-be97-4671-90b20b8afbc5/mzl.ahcrngmv.jpg/696x696bb.jpg",
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple123/v4/31/db/05/31db0547-531a-9de2-f72b-895c4c1b61cf/mzl.idrgbggn.jpg/696x696bb.jpg"
                ],
                "supportedDevices": [
                    "iPad2Wifi-iPad2Wifi",
                    "iPad23G-iPad23G",
                    "iPhone4S-iPhone4S",
                    "iPadThirdGen-iPadThirdGen",
                    "iPadThirdGen4G-iPadThirdGen4G",
                    "iPhone5-iPhone5",
                    "iPodTouchFifthGen-iPodTouchFifthGen",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPadMini-iPadMini",
                    "iPadMini4G-iPadMini4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [
                    "드문/경미한 만화 또는 비현실적 폭력"
                ],
                "kind": "software",
                "features": [],
                "trackCensoredName": "폰테마샵 Phone Themshop - 카톡테마와 배경",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%ED%8F%B0%ED%85%8C%EB%A7%88%EC%83%B5-phone-themshop-%EC%B9%B4%ED%86%A1%ED%85%8C%EB%A7%88%EC%99%80-%EB%B0%B0%EA%B2%BD/id960991407?mt=8&uo=4",
                "contentAdvisoryRating": "9+",
                "averageUserRatingForCurrentVersion": 3.0,
                "languageCodesISO2A": [
                    "EN",
                    "JA",
                    "KO"
                ],
                "fileSizeBytes": "147343360",
                "sellerUrl": "http://www.ptsapp.co.kr/",
                "userRatingCountForCurrentVersion": 38,
                "trackContentRating": "9+",
                "trackId": 960991407,
                "trackName": "폰테마샵 Phone Themshop - 카톡테마와 배경",
                "currentVersionReleaseDate": "2019-05-25T08:29:11Z",
                "minimumOsVersion": "9.0",
                "releaseNotes": "- PTS#샵 리스트 오류 수정\n- 특정 메뉴 선택시 앱 종료이슈 수정",
                "sellerName": "jung myungwon",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "1.0.31",
                "genreIds": [
                    "6012",
                    "6008"
                ],
                "formattedPrice": "무료",
                "artistId": 435666963,
                "artistName": "iConnect",
                "genres": [
                    "라이프 스타일",
                    "사진 및 비디오"
                ],
                "price": 0.00,
                "description": "\"아이폰 전용 카카오톡 테마 & 배경화면 다운로드 서비스\" \n\"2,000만 다운로드! 폰꾸미기/엔터테인먼트 랭킹 1위\"\n\"아티스트들의 고퀄리티 카카오톡 테마와 10,000+ 멋진 무료 배경화면\"\n\"카카오톡 테마 등 폰꾸미기 콘텐츠 최다 보유\"\n\n■ 기능소개\n\n•  아이폰 카톡 전용 테마 \n\n아티스트들이 직접 만든 고퀄리티의 아이폰 카톡테마들을 만나보세요. 심플, 소녀감성, 귀여운 캐릭터, 멋진 일러스트, 아이돌, 연예인 등 내가 찾는 스타일의 카톡테마들이 다 모여있어요.\n\n다운로드한 테마는 카톡 설정 페이지에서 원터치로 적용가능합니다. 앞으로 더욱더 다양하고 멋진 신상 테마들이 매일 업데이트될 예정이니 기대해주세요. ^^\n\n• 10,000개 이상의 배경화면 \n\n최신, 인기, 카테고리 별로 분류되어 원하는 배경화면을 손쉽게 찾을 수 있어요. \n\n에디터들이 엄선한 감성, 사랑, 계절, 패션, 꽃, 풍경, 도시. 야경, 동물, 디저트, 라이프 스타일, 빈티지, 캐릭터/일러스트, 코믹/유머, 캘리그라피, 패턴, 심플, 흑백 등 다양한 스타일의 멋진 배경을 무료로 이용하실 수 있습니다.\n\n■ 프리패스\n\n폰테마샵은 무료로 다운로드 가능하며 등록된 배경화면 콘텐츠는 모두 무료로 이용하실 수 있습니다. 무료 카카오톡 테마는 매주 꾸준히 업데이트됩니다. ^_^\n\n프리미엄 카카오톡 테마의 경우 프리패스 아이템을 구매하시면 기간내 무제한으로 다운로드 가능합니다.\n\n• 7일 프리패스 : USD 1.09\n• 30일 프리패스 : USD 2.09 \n• 360일 프리패스 : USD 12.09 \n\n※ 프리패스 기간동안에는 프리미엄 테마를 포함하여 폰 테마샵에 등록된 모든 콘텐츠를 무제한으로 이용하실 수 있습니다. \n\n※  카카오톡 테마는 한번 다운로드하면 mp3 파일처럼 영구적으로 소장할 수 있는 상품이 아닙니다. 이용기간 종료 후 이용했던 테마를 재다운로드하려면 프리패스 이용권이 필요한 점 이용시 참고해주세요. \n\n※  프리패스 구매시 iTunes 계정에 등록된 신용카드로 금액이 청구됩니다. 구독상품이 아니기때문에 기간이 지나도 절대 자동적으로 과금되지 않습니다. 아이템 구매와 관련된 정보는 [앱 > 더보기 > 내 구매정보] 에서 확인하실 수 있습니다.\n\n■ 고객지원\n\n사용 중 궁금한 사항이나 오류가 생기면 아래 폰 테마샵 고객지원팀으로 문의를 남겨주세요. 최대한 빠른 도움 드릴 수 있도록 하겠습니다.\n\n• 카카오톡 : 친구검색 ‘폰테마샵’ \n• 앱 : 더보기 > 1:1 문의하기 \n• 이메일 : help.ic@i-connect.co.kr\n\n■ 폰 테마샵 공식채널\n\n• 홈페이지 : http://www.ptsapp.co.kr/\n• 카카오스토리 : 친구검색 ‘폰테마샵’",
                "bundleId": "com.iconnect.Phone-Theme-Shop",
                "releaseDate": "2015-04-15T00:46:20Z",
                "primaryGenreName": "Lifestyle",
                "primaryGenreId": 6012,
                "averageUserRating": 3.5,
                "userRatingCount": 3945
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/kakao-mobility-corp/id1266185413?mt=8&uo=4",
                "artworkUrl60": "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/ec/6e/2f/ec6e2f9a-6f14-72c0-cfab-19786923a1f3/source/60x60bb.jpg",
                "artworkUrl100": "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/ec/6e/2f/ec6e2f9a-6f14-72c0-cfab-19786923a1f3/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/ec/6e/2f/ec6e2f9a-6f14-72c0-cfab-19786923a1f3/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/50/35/df/5035df93-b2aa-627a-411a-f2d717b6f137/mzl.dnojopds.png/696x696bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/4c/61/a2/4c61a283-4c5f-d72d-cc32-2fcfbeabe778/mzl.tdighwmr.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/3a/ca/dd/3acadda6-61bb-4563-4009-5ca3e9c89929/mzl.mfvgguen.png/696x696bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/27/08/ed/2708ed0a-21a0-e988-b68d-de7c4b4cbc3a/mzl.iltskmsl.png/696x696bb.png",
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/f3/c3/87/f3c387af-783c-bc8d-32fe-c468a5163455/mzl.qrtggpoa.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/8d/52/9c/8d529c00-2293-a5b5-4059-18c04b4f5904/mzl.tfapbyjb.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "iPhone5-iPhone5",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [],
                "trackCensoredName": "카카오 T",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4-t/id981110422?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 5.0,
                "languageCodesISO2A": [
                    "EN",
                    "JA",
                    "KO"
                ],
                "fileSizeBytes": "215874560",
                "sellerUrl": "http://service.kakaomobility.com/kakaot/",
                "userRatingCountForCurrentVersion": 3664,
                "trackContentRating": "4+",
                "trackId": 981110422,
                "trackName": "카카오 T",
                "currentVersionReleaseDate": "2019-05-29T05:04:23Z",
                "minimumOsVersion": "10.0",
                "releaseNotes": "[업데이트] \n1. 고장나거나 방치된 주변의 바이크를 자유롭게 제보할 수 있는 기능을 추가했습니다. \n2. 현재 내 위치와 지도를 실시간으로 볼 수 있도록 택시 탑승중 화면을 개선했습니다.",
                "sellerName": "Kakao Mobility Corp.",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "3.6.5",
                "genreIds": [
                    "6003"
                ],
                "formattedPrice": "무료",
                "artistId": 1266185413,
                "artistName": "Kakao Mobility Corp.",
                "genres": [
                    "여행"
                ],
                "price": 0.00,
                "description": "카카오택시가 카카오 T로 새로워졌습니다.\n더 많이 움직이고, 만나고, 경험하도록\n카카오 T가 만드는 새로운 변화를 만나보세요!\n\n■ 카카오 T\n• 택시(Taxi) 호출 앱에서 나아가, 이동 수단의 모든 것(Transportation)을 의미\n\n■ 어디갈 때, 앱 하나로\n•  택시, 대리운전, 주차, 내비, 카풀, 바이크까지 카카오 T 하나로!\n\n■ 믿고 부르는 택시\n•  빠르고 간편한 택시 호출\n•  편안함을 더한 고급택시 블랙\n\n■ 카풀로 함께가는 출퇴근길\n•  가는 방향이 같은 주변 차량과 매칭\n•  출퇴근 길 이동을 더 자유롭게\n\n■ 세상 편한 대리운전\n•  앱으로 편리하게 호출하고 안심하고 이용하는 대리운전\n\n■ 주차 고민 끝\n•  주변 주차장을 검색, 예약, 결제까지\n\n■ 가까운 곳 갈 땐, 걷지 말고 바이크\n•  걷기도 타기도 애매한 거리\n•  이젠 전동바이크로 부담없이 편하고 빠르게\n(인천 연수구/경기도 성남시만 이용 가능)\n\n■ 가장 빠른 길 안내 \n•  실시간 교통 정보 기반 빠르고 정확한 길 안내\n\n■ 더 간편한 결제\n•  카드 등록 한 번으로, 주차/대리 이용 요금 결제\n\n※ 사용자는 카카오 T의 원활한 이용을 위해 아래의 권한을 허용할 수 있습니다. 각 권한은 그 속성에 따라 반드시 허용해야 하는 필수 권한과 선택적으로 허용이 가능한 선택 권한으로 나뉩니다.\n\n1) 위치(필수): 내 위치 정보를 확인하여 최적의 위치를 추천받고, 위치를 반드시 필요로 하는 서비스를 이용하기 위해 필요한 권한 \n2) 알림(선택): 내 기기에서 호출한 카카오 T 각 서비스의 알림을 수신하기 위해 필요한 권한\n3) 사진첩(선택): 카카오 T 각 서비스 이용 건에 대한 영수증 저장을 위해 필요한 권한\n4) 마이크(선택): 카카오 T에서 음성 인식을 통해 출발지/도착지를 설정하기 위해 필요한 권한\n\n※ 선택 접근 권한은 동의하지 않아도 서비스를 이용할 수 있습니다.",
                "bundleId": "com.kakao.taxi",
                "releaseDate": "2015-04-02T01:04:53Z",
                "primaryGenreName": "Travel",
                "primaryGenreId": 6003,
                "averageUserRating": 5.0,
                "userRatingCount": 388709
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/kakao-corp/id362057950?mt=8&uo=4",
                "artworkUrl60": "https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/fb/86/42/fb86428a-fca6-c983-9560-d7e0422cc396/source/60x60bb.jpg",
                "artworkUrl100": "https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/fb/86/42/fb86428a-fca6-c983-9560-d7e0422cc396/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is4-ssl.mzstatic.com/image/thumb/Purple124/v4/fb/86/42/fb86428a-fca6-c983-9560-d7e0422cc396/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/bc/e8/7c/bce87c89-fabe-3103-a8c4-b6d2cda59ba2/mzl.rjqthlga.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/be/33/0b/be330bf0-ab12-015f-5958-07e8bdec4a9a/mzl.sdthrlcb.png/696x696bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/85/23/97/852397ca-15c1-a464-cbfb-25316c24b315/pr_source.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/87/1b/7e/871b7e89-39a2-a10f-2c23-760df4e23d13/pr_source.png/696x696bb.png",
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/0d/cf/48/0dcf4805-6e02-8022-f8f7-19a4f52640cf/mzl.ytejqqnz.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "iPhone5-iPhone5",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [],
                "trackCensoredName": "헤이카카오 Hey Kakao",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%ED%97%A4%EC%9D%B4%EC%B9%B4%EC%B9%B4%EC%98%A4-hey-kakao/id1286618447?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 2.0,
                "languageCodesISO2A": [
                    "KO"
                ],
                "fileSizeBytes": "43505664",
                "userRatingCountForCurrentVersion": 31,
                "trackContentRating": "4+",
                "trackId": 1286618447,
                "trackName": "헤이카카오 Hey Kakao",
                "currentVersionReleaseDate": "2019-02-13T05:09:43Z",
                "minimumOsVersion": "10.0",
                "releaseNotes": "• 서비스 안정성 및 일부 기능 개선",
                "sellerName": "Kakao Corp.",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "1.9.5",
                "genreIds": [
                    "6012",
                    "6007"
                ],
                "formattedPrice": "무료",
                "artistId": 362057950,
                "artistName": "Kakao Corp.",
                "genres": [
                    "라이프 스타일",
                    "생산성"
                ],
                "price": 0.00,
                "description": "일상을 바꾸는 한 마디, hey kakao.\n이제 생활속에서 더 쉽고 편하게 불러보세요.\n\n헤이카카오 앱은 스마트 스피커 카카오미니를 연결 및 관리하는 설정앱입니다.\n\n[헤이카카오 앱 주요기능]\n• 카카오미니를 연결, 관리, 제어할 수 있어요.\n- 카카오미니를 Wi-Fi 네트워크에 연결\n- 음악 감상을 위해 멜론 계정 로그인\n- 카카오톡 사용 설정 기능\n- 카카오 T 택시 사용 설정 기능\n- 기기 볼륨, 외부 스피커 연결 등 기기 제어\n- 기기 위치, 시간대, 호출명령어 등 기기 설정\n- 추천 명령어와 새로운 기능 확인\n\n\n카카오미니에서 헤이카카오를 더 쉽고 편하게,\n이제 카카오미니를 깨워 음성명령을 해 보세요. \n\n[헤이카카오가 할 수 있는 일]\n• 음성명령으로 다양한 기능을 사용할 수 있어요.\n- 당신의 취향에 맞는 음악 감상\n- 음성으로 카카오톡 보내기\n- 택시호출, 주문/배달 등 O2O 서비스 호출\n- 아이의 이름이 들어간 칭찬과 동화, 키즈 서비스\n- 인기 라디오, 팟캐스트 청취\n- 시간 관리를 도와주는 알람, 타이머\n- 날씨, 뉴스, 날짜, 시간 등 생활편의 기능\n- 교통정보, TV/영화/스포츠, 생활정보 등 검색 기능\n- 주식, 환율, 로또, 인물, 어학/사전 등 검색 기능\n- 놓치기 쉬운 일정, 까먹기 쉬운 메모 관리\n- 심심할 때 게임과 일상대화 기능\n\n\n카카오미니의 기능은 https://kakao.ai에서 확인할 수 있어요.",
                "bundleId": "com.kakao.i.connect",
                "releaseDate": "2017-10-18T05:20:13Z",
                "primaryGenreName": "Lifestyle",
                "primaryGenreId": 6012,
                "averageUserRating": 2.5,
                "userRatingCount": 462
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/kakaobank/id1258016943?mt=8&uo=4",
                "artworkUrl60": "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/06/11/c5/0611c5fb-0a52-1a61-c9c2-9217755ee2ea/source/60x60bb.jpg",
                "artworkUrl100": "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/06/11/c5/0611c5fb-0a52-1a61-c9c2-9217755ee2ea/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/06/11/c5/0611c5fb-0a52-1a61-c9c2-9217755ee2ea/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/62/d9/a4/62d9a44f-7983-4faa-674b-1631d1f25d21/mzl.sldpcxcq.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple123/v4/01/1b/b6/011bb6b5-ea6c-c373-f450-797a20437b24/mzl.nizoqokc.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/c8/76/94/c87694ae-5191-5357-aab4-4b27b7fdef90/mzl.voybnvti.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/8f/2d/f7/8f2df75e-d88e-d055-76ac-64d7ef9d76be/mzl.ncxozolh.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/2c/de/b8/2cdeb89c-212c-04c4-f138-9526ccfa3fec/mzl.hkxoitwp.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/06/f8/a0/06f8a015-d97b-7160-24e0-2906171351f0/mzl.aosvwpzk.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple113/v4/0f/5e/7f/0f5e7f08-4087-629e-f884-8f470e0515af/mzl.nuxthomm.png/696x696bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/80/6b/53/806b5345-0de9-8f59-dcf1-fac2c35a4593/mzl.gcjmmajo.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "iPad2Wifi-iPad2Wifi",
                    "iPad23G-iPad23G",
                    "iPhone4S-iPhone4S",
                    "iPadThirdGen-iPadThirdGen",
                    "iPadThirdGen4G-iPadThirdGen4G",
                    "iPhone5-iPhone5",
                    "iPodTouchFifthGen-iPodTouchFifthGen",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPadMini-iPadMini",
                    "iPadMini4G-iPadMini4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [],
                "trackCensoredName": "카카오뱅크 - 같지만 다른 은행",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4%EB%B1%85%ED%81%AC-%EA%B0%99%EC%A7%80%EB%A7%8C-%EB%8B%A4%EB%A5%B8-%EC%9D%80%ED%96%89/id1258016944?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 3.5,
                "languageCodesISO2A": [
                    "KO"
                ],
                "fileSizeBytes": "276418560",
                "sellerUrl": "https://www.kakaobank.com/",
                "userRatingCountForCurrentVersion": 81,
                "trackContentRating": "4+",
                "trackId": 1258016944,
                "trackName": "카카오뱅크 - 같지만 다른 은행",
                "currentVersionReleaseDate": "2019-05-28T08:05:49Z",
                "minimumOsVersion": "9.0",
                "releaseNotes": "• 한도조회부터 입금까지, 간편하고 빠른 개인사업자 대출 출시\n• 입출금통장 관리 메뉴에 연결된 증권계좌 정보 표시\n• 체크카드 배송지 변경 기능 및 배송업체 정보 제공\n• 안정성 및 접근성 개선\n\n더 좋은 앱을 제공하기 위해 고민하고 개선해 나가겠습니다.\n일상에서 더 쉽게, 더 자주 이용하는 은행이 되겠습니다.",
                "sellerName": "Korea Kakao, Corp.",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "1.15.0",
                "genreIds": [
                    "6015"
                ],
                "formattedPrice": "무료",
                "artistId": 1258016943,
                "artistName": "Kakaobank",
                "genres": [
                    "금융"
                ],
                "price": 0.00,
                "description": "일상에서 더 쉽게, 더 자주 만나는 금융혁신\n1금융권 은행 카카오뱅크\n\n■ 새롭게 디자인된 은행\n• 365일 언제나 지점 방문 없이 모든 은행 업무를 모바일에서\n• 7분만에 끝나는 쉬운 계좌개설\n\n■ 쉬운 사용성\n• 공인인증서, 보안카드 없는 계좌이체\n• 계좌번호를 몰라도 카톡 친구에게 간편 송금 (상대방이 카카오뱅크 고객이 아니어도 송금 가능)\n\n■ 내 취향대로 선택\n• 카카오프렌즈 캐릭터 디자인부터 고급스러운 블랙 컬러까지, 세련된 디자인의 체크카드\n• 내 마음대로 설정하는 계좌 이름과 색상\n\n■ 눈에 보이는 혜택\n• 복잡한 가입 조건이나 우대 조건 없이, 누구에게나 경쟁력있는 금리와 혜택 제공\n• 늘어나는 이자를 실시간으로 확인할 수 있는 정기예금\n• 만 19세 이상 대한민국 국민의 90%가 신청 가능한 비상금대출(소액 마이너스대출)\n\n■ 카카오프렌즈와 함께하는 26주적금\n• 천원부터 차곡차곡 26주동안 매주 쌓는 적금\n• 카카오프렌즈 응원과 함께하면 어느덧 만기 달성이 눈앞에!\n\n■ 함께쓰고 같이보는 모임통장\n• 손쉽게 카카오톡 친구들을 멤버로 초대 \n• 잔액과 입출금 현황을 멤버들과 함께 보기 \n• 위트있는 메시지카드로 회비 요청\n\n■ 소중한 ‘내 신용정보’ 관리\n• 제1금융권에서 안전하게 무료로 내 신용정보 확인\n• 신용 변동내역 발생 시 알림 서비스 및 신용정보 관리 꿀팁 제공\n\n■ 파격적인 수수료로 해외송금\n• 365일 언제 어디서든 이용 가능한 해외송금 (보내기 및 받기)\n• 해외계좌 및 웨스턴유니온(WU)을 통해 전세계 200여개국으로 해외송금 가능\n• 거래외국환은행 지정, 연장 업무도 지점방문없이 모바일에서 신청 가능  \n\n■ 제휴 증권사 계좌 개설 서비스\n• 카카오뱅크에서 간편하게 주식계좌 개설 가능\n• 평생 거래 수수료 무료 등 다양한 혜택 제공\n\n■ 이체수수료 및 입출금 수수료 면제\n• 타행 이체 및 자동이체 수수료 면제\n• 전국 CU, 세븐일레븐 편의점 ATM 입금/출금/이체 수수료 면제\n• ATM (모든 은행, 제휴 VAN사 기기) 입금/출금/이체 수수료 면제\n\n* 국내 모든 VAN사 (한국전자금융, 롯데피에스넷, 효성티앤에스, 한네트, 청호이지캐쉬, 에이티엠플러스)와 제휴되어 있으며, ATM/CD기 입금/출금/이체 수수료는 향후 정책에 따라 변경될 수 있습니다. 정책이 변경되는 경우 시행 1개월 전에 카카오뱅크 앱 및 홈페이지를 통해 미리 알려드립니다.\n\n■ 고객센터 운영 시간 안내\n• 예/적금, 대출, 카드 문의 : 1599-3333 (09:00 ~ 22:00 365일) \n• 전월세 보증금 대출, 외환 문의 : 1599-3333 (09:00 ~ 18:00 평일) \n• 사고 신고 : 1599-8888 (24시간 365일)\n\n■ 챗봇 운영 시간 안내 \n• 카카오톡 플러스친구 \"카카오뱅크 고객센터\" (24시간 365일)\n\n■ 카카오뱅크 앱 이용을 위한 권한 및 목적 안내\n• 카메라(선택) : 신분증 촬영 및 서류 제출, 영상통화, 프로필 사진 등록\n• 사진(선택) : 이체⁄송금⁄출금 확인증, 카드매출전표 저장\n• 위치(선택) : 부정가입방지 및 부정거래탐지\n\n * 선택 접근권한은 동의하지 않아도 서비스를 이용하실 수 있습니다.",
                "bundleId": "com.kakaobank.channel",
                "releaseDate": "2017-07-26T15:24:27Z",
                "primaryGenreName": "Finance",
                "primaryGenreId": 6015,
                "averageUserRating": 3.5,
                "userRatingCount": 5918
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/dongwoo-son/id438071621?mt=8&uo=4",
                "artworkUrl60": "https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/3c/8a/97/3c8a97d8-446c-5128-6cb5-71440c2774c5/source/60x60bb.jpg",
                "artworkUrl100": "https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/3c/8a/97/3c8a97d8-446c-5128-6cb5-71440c2774c5/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/d2/c6/72/d2c6726b-61fd-ca43-7e8c-e12b59615edf/pr_source.png/1024x768bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/dd/63/6a/dd636a23-57c9-1899-be3d-98ee886f27d7/pr_source.png/1024x768bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple118/v4/46/f4/70/46f470d3-b6fe-00c8-d055-831fe93f5956/pr_source.png/1024x768bb.png"
                ],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is3-ssl.mzstatic.com/image/thumb/Purple128/v4/3c/8a/97/3c8a97d8-446c-5128-6cb5-71440c2774c5/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple118/v4/3e/72/f3/3e72f377-6563-0ec6-ad28-cb3dcd47b08b/pr_source.png/696x696bb.png",
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple128/v4/09/40/b6/0940b677-7b69-3f8d-626f-569c305a5bca/pr_source.png/696x696bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple118/v4/50/44/7c/50447ca8-d0f3-af74-1f83-04623199f2b0/pr_source.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "iPad2Wifi-iPad2Wifi",
                    "iPad23G-iPad23G",
                    "iPhone4S-iPhone4S",
                    "iPadThirdGen-iPadThirdGen",
                    "iPadThirdGen4G-iPadThirdGen4G",
                    "iPhone5-iPhone5",
                    "iPodTouchFifthGen-iPodTouchFifthGen",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPadMini-iPadMini",
                    "iPadMini4G-iPadMini4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [
                    "iosUniversal"
                ],
                "trackCensoredName": "손그림 - 사진에 그림 그려서 카카오, 인스타그램 공유",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%EC%86%90%EA%B7%B8%EB%A6%BC-%EC%82%AC%EC%A7%84%EC%97%90-%EA%B7%B8%EB%A6%BC-%EA%B7%B8%EB%A0%A4%EC%84%9C-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EC%9D%B8%EC%8A%A4%ED%83%80%EA%B7%B8%EB%9E%A8-%EA%B3%B5%EC%9C%A0/id579958634?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 4.0,
                "languageCodesISO2A": [
                    "EN",
                    "JA",
                    "KO",
                    "ZH"
                ],
                "fileSizeBytes": "10926080",
                "userRatingCountForCurrentVersion": 23,
                "trackContentRating": "4+",
                "trackId": 579958634,
                "trackName": "손그림 - 사진에 그림 그려서 카카오, 인스타그램 공유",
                "currentVersionReleaseDate": "2017-12-06T23:42:30Z",
                "minimumOsVersion": "8.0",
                "releaseNotes": "- 아이폰X 대응\n- 2017년에 어울리는 UI로 변경\n- 검정색 쉽게 고를 수 있도록 변경\n- 저장하기 한번에 누를 수 있도록 따로 메뉴에 넣기\n- 확대해서 저장하면 깨지던 버그 수정",
                "sellerName": "DONG WOO SON",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "10",
                "genreIds": [
                    "6008",
                    "6007"
                ],
                "formattedPrice": "무료",
                "artistId": 438071621,
                "artistName": "Dongwoo Son",
                "genres": [
                    "사진 및 비디오",
                    "생산성"
                ],
                "price": 0.00,
                "description": "손그림으로 사진에 그림을 그려서 카카오나 인스타그램 친구들과 함께 공유해보세요.\n\n부드러운 붓터치는 당신의 사진에 활기를 불러 일으킬 거예요. \n\n물론 사진첩에 저장하는 기능도 있습니다.",
                "bundleId": "com.neoevoke.picdraw",
                "releaseDate": "2012-11-27T01:16:36Z",
                "primaryGenreName": "Photo & Video",
                "primaryGenreId": 6008,
                "averageUserRating": 3.5,
                "userRatingCount": 166
            },
            {
                "artistViewUrl": "https://itunes.apple.com/kr/developer/kakao-mobility-corp/id1266185413?mt=8&uo=4",
                "artworkUrl60": "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/66/97/b4/6697b4e2-6f42-b629-1e74-132ab10a7d18/source/60x60bb.jpg",
                "artworkUrl100": "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/66/97/b4/6697b4e2-6f42-b629-1e74-132ab10a7d18/source/100x100bb.jpg",
                "isGameCenterEnabled": false,
                "ipadScreenshotUrls": [
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/0c/0a/7e/0c0a7ef2-436e-57d2-c043-0e95b2bc95f3/pr_source.png/1024x768bb.png",
                    "https://is5-ssl.mzstatic.com/image/thumb/Purple123/v4/6d/09/a0/6d09a01f-6815-d8cd-7660-fd043d9ef80b/pr_source.png/1024x768bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/af/4b/25/af4b2587-a34f-db32-beae-7d21ec677409/pr_source.png/1024x768bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/b2/41/07/b24107f0-8bda-beb5-aef3-49afdfe2931c/pr_source.png/1024x768bb.png",
                    "https://is4-ssl.mzstatic.com/image/thumb/Purple113/v4/ed/a8/3f/eda83f93-51bf-97bf-0357-a37c06c5d244/pr_source.png/1024x768bb.png"
                ],
                "appletvScreenshotUrls": [],
                "artworkUrl512": "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/66/97/b4/6697b4e2-6f42-b629-1e74-132ab10a7d18/source/512x512bb.jpg",
                "screenshotUrls": [
                    "https://is1-ssl.mzstatic.com/image/thumb/Purple113/v4/3e/53/9c/3e539c70-a194-73f3-2c75-8190afb70403/mzl.hxagmguy.png/696x696bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple113/v4/4e/bf/af/4ebfafe0-6b02-6135-47ef-7e5f25fa3572/mzl.nesrsvgd.png/696x696bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple123/v4/48/cc/30/48cc3004-6c23-ead2-284d-c8ae6b294a55/mzl.loekpvqk.png/696x696bb.png",
                    "https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/d4/a4/7a/d4a47abe-4051-e952-4d75-17037c8da4ef/mzl.gbbnzcbv.png/696x696bb.png",
                    "https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/9b/58/33/9b583330-bd7a-bb24-c6b0-3ba939334124/mzl.wsmvkngf.png/696x696bb.png"
                ],
                "supportedDevices": [
                    "iPhone5-iPhone5",
                    "iPadFourthGen-iPadFourthGen",
                    "iPadFourthGen4G-iPadFourthGen4G",
                    "iPhone5c-iPhone5c",
                    "iPhone5s-iPhone5s",
                    "iPadAir-iPadAir",
                    "iPadAirCellular-iPadAirCellular",
                    "iPadMiniRetina-iPadMiniRetina",
                    "iPadMiniRetinaCellular-iPadMiniRetinaCellular",
                    "iPhone6-iPhone6",
                    "iPhone6Plus-iPhone6Plus",
                    "iPadAir2-iPadAir2",
                    "iPadAir2Cellular-iPadAir2Cellular",
                    "iPadMini3-iPadMini3",
                    "iPadMini3Cellular-iPadMini3Cellular",
                    "iPodTouchSixthGen-iPodTouchSixthGen",
                    "iPhone6s-iPhone6s",
                    "iPhone6sPlus-iPhone6sPlus",
                    "iPadMini4-iPadMini4",
                    "iPadMini4Cellular-iPadMini4Cellular",
                    "iPadPro-iPadPro",
                    "iPadProCellular-iPadProCellular",
                    "iPadPro97-iPadPro97",
                    "iPadPro97Cellular-iPadPro97Cellular",
                    "iPhoneSE-iPhoneSE",
                    "iPhone7-iPhone7",
                    "iPhone7Plus-iPhone7Plus",
                    "iPad611-iPad611",
                    "iPad612-iPad612",
                    "iPad71-iPad71",
                    "iPad72-iPad72",
                    "iPad73-iPad73",
                    "iPad74-iPad74",
                    "iPhone8-iPhone8",
                    "iPhone8Plus-iPhone8Plus",
                    "iPhoneX-iPhoneX",
                    "iPad75-iPad75",
                    "iPad76-iPad76",
                    "iPhoneXS-iPhoneXS",
                    "iPhoneXSMax-iPhoneXSMax",
                    "iPhoneXR-iPhoneXR",
                    "iPad812-iPad812",
                    "iPad834-iPad834",
                    "iPad856-iPad856",
                    "iPad878-iPad878",
                    "Watch4-Watch4",
                    "iPadMini5-iPadMini5",
                    "iPadMini5Cellular-iPadMini5Cellular",
                    "iPadAir3-iPadAir3",
                    "iPadAir3Cellular-iPadAir3Cellular",
                    "iPodTouchSeventhGen-iPodTouchSeventhGen"
                ],
                "advisories": [],
                "kind": "software",
                "features": [
                    "iosUniversal"
                ],
                "trackCensoredName": "카카오내비",
                "trackViewUrl": "https://itunes.apple.com/kr/app/%EC%B9%B4%EC%B9%B4%EC%98%A4%EB%82%B4%EB%B9%84/id417698849?mt=8&uo=4",
                "contentAdvisoryRating": "4+",
                "averageUserRatingForCurrentVersion": 3.0,
                "languageCodesISO2A": [
                    "EN",
                    "KO"
                ],
                "fileSizeBytes": "134162432",
                "sellerUrl": "http://www.kakao.com/services/67/",
                "userRatingCountForCurrentVersion": 44,
                "trackContentRating": "4+",
                "trackId": 417698849,
                "trackName": "카카오내비",
                "currentVersionReleaseDate": "2019-06-01T02:41:32Z",
                "minimumOsVersion": "10.0",
                "releaseNotes": "복합 쇼핑몰, 공항처럼 여러 주차장과 출입구를 지닌 목적지를 방문하실 때, 원하는 방향으로 진입할 수 있도록 개선하였습니다. 그 밖에도 편리하고 안전한 서비스 제공을 위해 UI 개선 및 기능을 추가하였습니다.\n[주요 업데이트 내용] \n- 검색 결과 > 진입지점 PIN 표시 (건물 기준)\n- 주행 UI 디자인 개선 \n- CarPlay 폰화면에서 야간모드 제공\n- Carplay 퀵버튼 기능 추가",
                "sellerName": "Kakao Mobility Corp.",
                "isVppDeviceBasedLicensingEnabled": true,
                "currency": "KRW",
                "wrapperType": "software",
                "version": "3.36.1",
                "genreIds": [
                    "6010"
                ],
                "formattedPrice": "무료",
                "artistId": 1266185413,
                "artistName": "Kakao Mobility Corp.",
                "genres": [
                    "내비게이션"
                ],
                "price": 0.00,
                "description": "즐거움이 다른 길안내를 시작합니다. \n내비게이션의 새로운 진화, 카카오내비! \n\n■ 빠르고 정확한 길안내 \n이용자들의 실제 운행 데이터와 실시간 교통정보를 바탕으로 찾은 최적의 길로 막힘없이 시원하게 달려보세요. \n\n■ 즐거운 운전 도우미 \n뽀로로, 헤이지니, 사투리 등 다양한 길안내 음성과 귀여운 내 차 아이콘, 그리고 내비 곳곳에 숨어 있는 카카오프렌즈와 함께라면 운전이 더욱 즐거워집니다. \n\n■ 빅데이터로 예측하는 미래운행정보 \n언제 출발해야 덜 밀릴지 고민하지 마세요! 출발 시간에 따라 목적지까지 얼마나 걸리는지를 빅데이터와 교통 예측 알고리즘을 기반으로 알려 드려요. \n\n■ CarPlay에서 만나는 내비게이션 \n스마트폰을 연결하면 카카오내비가 더 큰 화면으로 쏘옥! 차량용 디스플레이와 오디오에 최적화된 길안내로 더욱 편하게 운전하세요. (CarPlay 지원 차량, 헤드유닛에서만 가능) \n\n■ 카톡으로 전하는 실시간 위치 \n어디서 만날지, 어디쯤인지 일일이 설명하기 힘들죠? 약속 장소, 도착시간, 내 위치를 카톡으로 간편하게 설명하세요! \n\n자동차로 어디를 가든 이제 카카오내비와 함께하세요! \n\n**유의사항** \n- 백그라운드 모드에서 GPS 사용으로 인하여 배터리 소모량이 증가할 수 있습니다. \n- IPhone4S에서는 일부 성능 저하가 발생할 수 있습니다. \n\n■ 카카오내비 사용을 위해 필요한 접근 권한 \n[필수적 접근권한] \n* 위치 - 길안내, 벌집 화면 구성, 주변검색을 위해 접근이 필요합니다. \n[선택적 접근권한] \n* 사진 - 벌집 화면 편집 꾸미기에 접근이 필요합니다. \n* 마이크 - 음성 인식 기능과 블랙박스 음성 녹화 시 접근이 필요합니다. \n* 카메라 - 블랙박스 기능과 벌집 화면 꾸미기에 접근이 필요합니다. \n* 셀룰러 데이터 - 위치정보, 검색정보, 경로 계산 등 서비스를 위한 각종 데이터 송수신을 위해 접근이 필요합니다. \n\n※ 선택적 접근권한의 허용에는 동의하지 않아도 서비스의 이용이 가능합니다.\n\n———— \n고객센터 : 플러스친구(채팅상담) / 365일 08시 ~ 25시\n긴급신고센터 : 1599-9400 (365일 24시간 운영)",
                "bundleId": "com.locnall.kimgisa",
                "releaseDate": "2011-03-10T22:53:41Z",
                "primaryGenreName": "Navigation",
                "primaryGenreId": 6010,
                "averageUserRating": 4.0,
                "userRatingCount": 21194
            }
        ]
    }
    """
}
